### ISSUE TITLE
Register?

### ISSUE THREAD

**Issue by cscherrer** [hendersontrent/PosteriorPlots.jl#56]
The sidebar says you're on v0.1.7, but
```julia
(@v1.7) pkg> add PosteriorPlots
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
    Updating registry at `~/.julia/registries/SLIMregistryJL`
    Updating git-repo `https://github.com/slimgroup/SLIMregistryJL.git`
ERROR: The following package names could not be resolved:
 * PosteriorPlots (not found in project, manifest or registry)
 
(@v1.7) pkg> 
 ```
Looks like it didn't go through correctly?

**Comment by hendersontrent** [comment]
It's currently in the waiting period for automatic merge onto the registry. The GitHub versions were mostly for me as I only recently submitted it to the registry for the first time the other day. However, as I mentioned in #53 I have some much better functionality and cleaner refactor of some code in #55 and `PosteriorPlots` will be much better once those are incorporated and then submitted to the registry after the initial version is on.

It's my first time formally submitting a Julia package and I'm learning Julia as I go as fast as I can (came from R and Stan), apologies for the bit of round-and-round on my behalf!

**Comment by cscherrer** [comment]
No worries, congrats on your first package!

**Comment by hendersontrent** [comment]
Thanks - it helps being able to look at really great examples such as `Soss` to learn from!
